### ISSUE TITLE
./nix2appimage.sh fails: /nix/store/.../bin/appimagetool: No such file or directory

### ISSUE THREAD

**Issue by bjornfor** [matthewbauer/nix-bundle#22]
```
$ ./nix2appimage.sh vlc
these derivations will be built:
  /nix/store/ryslsrgg7l1n8sr4v47vnvdfbw68v9h8-appimage.drv
building path(s) ‘/nix/store/q45h3wcl0xclsr8x4hkn3zh93kzb5lf4-appimage’
/nix/store/p4avr9pw3sa68ivryc490fvqmnws0zyv-stdenv/setup: line 853: /nix/store/kichfn29xdmzj8d4wg18d28fw9hkcxf2-appimagekit/bin/appimagetool: No such file or directory
builder for ‘/nix/store/ryslsrgg7l1n8sr4v47vnvdfbw68v9h8-appimage.drv’ failed with exit code 127
error: build of ‘/nix/store/ryslsrgg7l1n8sr4v47vnvdfbw68v9h8-appimage.drv’ failed
./nix2appimage.sh failed. Exiting.
```

**Comment by matthewbauer** [comment]
Can you verify that this is fixed in the latest merge? I've forgotten what all changed but I believe this might have been fixed

**Comment by bjornfor** [comment]
I got your appimage changes via git pull but it still fails with the same message.

**Comment by EchterAgo** [comment]
@bjornfor this is likely `binfmt_misc` registrations leaking into docker:

https://github.com/TheAssassin/AppImageLauncher/issues/407
